[package]
name = "haste_protobuf"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
prost = "0.12.3"
bytes = "1.5.0"

[build-dependencies]
glob = "0.3.1"
prost-build = "0.12.3"
